version: "3.7"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - django_static_volume:/home/app/web/static
      - media:/home/app/web/media
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env.prod.react
    volumes:
      - react_static_volume/:/app/build
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.prod
    volumes:
      - django_static_volume:/usr/src/app/django_files/static
      - media:/usr/src/app/media
      - react_static_volume:/usr/share/nginx/react
    ports:
      - 80:80

volumes:
  postgres_data:
  media:
  react_static_volume:
  django_static_volume:
