version: "3.7"

services:
  backend:
    user: "app:app"
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    command: gunicorn django_app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - django_static_volume:/home/app/web/static
      - media:/home/app/web/media
      - django_errors_logs:/home/app/web/logs
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:13.3-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    volumes:
      - react_static_volume/:/app/build
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    volumes:
      - django_static_volume:/usr/share/nginx/django_files/static
      - media:/usr/share/nginx/media
      - react_static_volume:/usr/share/nginx/react
    ports:
      - 80:80
    depends_on:
      - backend

volumes:
  postgres_data:
  media:
  react_static_volume:
  django_static_volume:
  django_errors_logs:
