# Generated by Django 3.2.5 on 2021-07-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210719_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PROCESS', 'Отправлено на согласование'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('DISAPPROVED', 'Не одобрено'), ('RETURNED', 'Отправлено на доработку')], default='REJECTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='statuschangedrecord',
            name='current_status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PROCESS', 'Отправлено на согласование'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('DISAPPROVED', 'Не одобрено'), ('RETURNED', 'Отправлено на доработку')], default='REJECTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='statuschangedrecord',
            name='previous_status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PROCESS', 'Отправлено на согласование'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('DISAPPROVED', 'Не одобрено'), ('RETURNED', 'Отправлено на доработку')], default='REJECTED', max_length=15),
        ),
        migrations.AlterField(
            model_name='user',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PROCESS', 'Отправлено на согласование'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('DISAPPROVED', 'Не одобрено'), ('RETURNED', 'Отправлено на доработку')], default='REJECTED', max_length=15),
        ),
    ]
