# Generated by Django 3.2.5 on 2021-07-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20210719_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Черновик'), ('PROCESS', 'Отправлено на согласование'), ('APPROVED', 'Одобрено'), ('REJECTED', 'Отклонено'), ('DISAPPROVED', 'Не одобрено'), ('RETURNED', 'Отправлено на доработку')], default='PROCESS', max_length=15),
        ),
    ]
