# Generated by Django 3.2.5 on 2021-07-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventorganization',
            name='role_description',
            field=models.CharField(blank=True, max_length=127),
        ),
        migrations.AlterField(
            model_name='eventorganization',
            name='role',
            field=models.CharField(choices=[('ORGANIZER', 'организатор'), ('CO_ORGANIZER', 'соорганизатор')], default='ORGANIZER', max_length=15),
        ),
        migrations.DeleteModel(
            name='EventOrganizationRole',
        ),
    ]
