# Generated by Django 3.2.5 on 2021-07-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20210721_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventorganization',
            name='role',
            field=models.CharField(choices=[('MAIN_ORGANIZER', 'организатор'), ('CO_ORGANIZER', 'соорганизатор')], default='MAIN_ORGANIZER', max_length=15),
        ),
    ]
