# Generated by Django 3.2.5 on 2021-07-23 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_eventorganization_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='academic_titles',
        ),
        migrations.RemoveField(
            model_name='user',
            name='proff_interests',
        ),
        migrations.AddField(
            model_name='statuschangedrecord',
            name='comment',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='ProffInterestUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proff_interest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='events.proffinterest')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proff_interests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AcademicTitleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_titles', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='events.academictitle')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='academic_titles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
