# Generated by Django 3.2.5 on 2021-07-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20210723_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academictitleuser',
            old_name='academic_titles',
            new_name='academic_title',
        ),
        migrations.RenameField(
            model_name='academictitleuser',
            old_name='users',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='proffinterestuser',
            old_name='users',
            new_name='user',
        ),
    ]
