# Generated by Django 3.1.2 on 2021-08-08 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20210730_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='brief_description',
            field=models.CharField(blank=True, max_length=1023),
        ),
        migrations.AlterField(
            model_name='event',
            name='full_description',
            field=models.CharField(blank=True, max_length=15000),
        ),
    ]
