# Generated by Django 3.1.2 on 2021-08-08 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210808_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='data_begin',
            new_name='date_begin',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='data_end',
            new_name='date_end',
        ),
    ]
